# frozen_string_literal: true

require:
  - rubocop-rspec
  - rubocop-performance

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
